services:
  dashboard:
    build:
      context: .
      args:
        VITE_API_URL: /api
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - nginx_default
    restart: unless-stopped

networks:
  nginx_default:
    external: true
