services:
  dashboard:
    build:
      context: .
      args:
        VITE_API_URL: /api
    networks:
      - medval
    restart: unless-stopped
    depends_on:
      - medval-backend

  medval-backend:
    build:
      context: ../medval-backend
    env_file:
      - ../medval-backend/.env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - medval
    restart: unless-stopped

networks:
  medval:
